version: "3"
services:
   mongo:
    hostname: mongonode
    container_name: mongonode
    image: mongo:4.0-xenial
    expose:
    - 27017
    ports:
      - 27017:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
